Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
	config.vm.provider :virtualbox do |vb|
        	vb.name = "Ubuntu1804"
	end
  config.vm.synced_folder "c:/work/vagrant1804/vagrant_data", "/var/vagrant_data"
  config.vm.host_name = "Ubuntu1804"
  config.vm.provision :shell, :path => "enviroment/install.sh"
  config.vm.provision "file", source: "file.txt", destination: "file.txt"
end
